# Site settings
title: موسسه حقوقی پوژمان زرین عدالت
email: eslami.amir76@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Custom Variables
content-title: موسسه حقوقی پوژمان
content-desc: > #
  ثبت شرکت هاو موسسات تجاری و غیرتجاری. ثبت برند و ثبت تغییرات و پلمب دفاتر تجاری. اخذ کد اقتصادی و کارت بازرگانی.
  مشاوره و پذیرش وکالت در امور حقوقی کیفری و خانواده و ثبت و غیره ...

about-we1: پس از سال ها فعالیت در زمینه های مختلف حقوقی, تصمیم گرفتیم که موسسه حقوقی پوژمان زرین عدالت را تاسیس کنیم. تا بتوانیم خدماتی را با بالاترین کیفیت ارايه کنیم. ما در موسسه حقوقی پوژمان سعی بر آن داریم تا با ارايه خدماتی تضمین شده رضایت مشتریانی که به موسسه ما اعتماد کرده اند را بدست بیاریم.
about-we2: ما در موسسه حقوقی پوژمان زرین عدالت می توانیم در زمینه های ثبت شرکت و موسسات تجاری - غیرتجاری, ثبت برند - ثبت تغییرات, پلمپ دفاتر تجاری, اخذ کد اقتصادی و کارت بازرگانی, مشاوره و پذیرش وکالت در امور حقوقی کیفری و خانواده و ثبت و غیره ... , آماده خدمت رسانی به مشتریان عزیز هستیم.

what-title1: ثبت شرکت
what-desc1: موسسه حقوقی پوژمان زرین عدالت در زمینه ثبت شرکت ها و موسسات تجاری - غیرتجاری می تواند به کمک کند تا بتوانید برند و یا شرکت خود را به ثبت برسانید.
what-title2: وکالت حقوقی
what-desc2: در زمینه های حقوقی کیفری و یا خانواده موسسه پوژمان می تواند به شما مشاوره بدهد و یا وکالت شما را در این زمینه ها به عهده بگیرد.
what-title3: عنوان کار
what-desc3: شرح وظایفی از کاری که انجام می دهیم در این قسمت نوشته میشود و با آن به خود می بالیم که بله این چنین است و ما اینکار را انجام میدهیم الکی مثالا!

contact-address: شهریار میدان جهاد ساختمان امین طبقه سوم واحد۱۹
contact-tell: ۵۶۲۹۹۴۲۲ - 021

# Build settings
markdown: kramdown
